### ISSUE TITLE
Keymapping

### ISSUE THREAD

**Issue by focussing** [christophgockel/atom-sftp-sync#5]
Hello!

When using sftp-deployment I could define a key binding like

`'cmd-shift-u': 'sftp-deployment:uploadCurrentFile'`

How does that work with atom-sftp-sync?
symply adding 

`'cmd-shift-u': 'atom-sftp-sync:uploadCurrentFile'`

does not work.

**Comment by christophgockel** [comment]
Might be a bit too late for your use case, but have you added this binding under the `'atom-text-editor'` context?

The entry in your keymap needs to look like this:

```
'atom-text-editor':
  'cmd-shift-u': 'atom-sftp-sync:uploadCurrentFile'
```

**Comment by focussing** [comment]
Yep, I am using VS Code right now, but thank you anyway!
